#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade not found on Wed Nov 29 23:37:04 2017
#

import wx
import json
import StringIO
# begin wxGlade: dependencies
import gettext
import shutil, os
import run_prolucid
import base64

# end wxGlade

# begin wxGlade: extracode
# end wxGlade
default_params_dict = {'java_path': '', 'fasta_path': '', 'precursor_ppm': '50', 'num_isotope': '3', 'min_mass': '600',
                       'max_mass': '6000', 'protease': 'trypsin', 'cleave_residue': 'KR',
                       'enzyme_spec': 2, 'max_miss_cleave': '2', 'stat_mod': '57.02146 C',
                       'diff_mod': 0, 'c_term_stat_mod': '', 'n_term_stat_mod': '',
                       'DTA_min_num_peptide': '2', 'DTA_min_num_tryptic_end': 2, 'FDR_level': 0,
                       'FDR_filter': '0.05', 'java_xmx':'8G', 'java_thread':'8'}  # FDR_level 0 protein, 1 peptide, 2 spectrum

FDR_level_dict = {1: 'peptide', 0: 'protein', 2: 'spectrum'}


class ProLuCID_GUI(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ProLuCID_GUI.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.text_fasta = wx.TextCtrl(self, wx.ID_ANY, "")
        self.button_fasta_path = wx.Button(self, wx.ID_ANY, _("..."))
        self.Bind(wx.EVT_BUTTON, self.onOpenFasta, self.button_fasta_path)
        self.text_java = wx.TextCtrl(self, wx.ID_ANY, "")
        self.button_java_path = wx.Button(self, wx.ID_ANY, _("..."))
        self.Bind(wx.EVT_BUTTON, self.onOpenJava, self.button_java_path)
        self.text_ms2s = wx.TextCtrl(self, wx.ID_ANY, "")
        self.button_ms2_path = wx.Button(self, wx.ID_ANY, _("..."))
        self.Bind(wx.EVT_BUTTON, self.onOpenMS2, self.button_ms2_path)
        self.text_java_xmx = wx.TextCtrl(self, wx.ID_ANY, _(default_params_dict['java_xmx']))
        self.text_java_thread = wx.TextCtrl(self, wx.ID_ANY, _(default_params_dict['java_thread']))
        self.text_precursor_ppm = wx.TextCtrl(self, wx.ID_ANY, _(default_params_dict['precursor_ppm']))
        self.text_num_isotope = wx.TextCtrl(self, wx.ID_ANY, _(default_params_dict['num_isotope']))

        self.text_min_mass = wx.TextCtrl(self, wx.ID_ANY, _(default_params_dict['min_mass']))
        self.text_max_mass = wx.TextCtrl(self, wx.ID_ANY, _(default_params_dict['max_mass']))
        self.text_protease = wx.TextCtrl(self, wx.ID_ANY, _(default_params_dict['protease']))
        self.text_cleave_residue = wx.TextCtrl(self, wx.ID_ANY, _(default_params_dict['cleave_residue']))
        self.combo_box_enzyme_specificity = wx.ComboBox(self, wx.ID_ANY, choices=[_("0: non specificity"), _("1: specific at one end"), _("2: specific at both ends")],
                                                        style=wx.CB_DROPDOWN)
        self.text_max_miss_cleave = wx.TextCtrl(self, wx.ID_ANY, _(default_params_dict['max_miss_cleave']))
        self.text_stat_mod = wx.TextCtrl(self, wx.ID_ANY, _(default_params_dict['stat_mod']))
        self.combo_box_diff_mod = wx.ComboBox(self, wx.ID_ANY, choices=["", _("79.966331 STY"), _("15.994915 M"), _("0.984016 NQ"), _("57.021464 C"), _("42.010565 K")],
                                              style=wx.CB_DROPDOWN)
        self.text_c_term_stat_mod = wx.TextCtrl(self, wx.ID_ANY, _(default_params_dict['c_term_stat_mod']))
        self.text_n_term_stat_mod = wx.TextCtrl(self, wx.ID_ANY, _(default_params_dict['n_term_stat_mod']))
        self.text_DTA_min_num_peptide = wx.TextCtrl(self, wx.ID_ANY, _(default_params_dict['DTA_min_num_peptide']))
        self.combo_box_DTA_ends = wx.ComboBox(self, wx.ID_ANY, choices=[_("0: allow non-tryptic"), _("1: one end"), _("2: both ends")], style=wx.CB_DROPDOWN)
        self.radio_box_FDR_level = wx.RadioBox(self, wx.ID_ANY, "", choices=[_("Protein level FDR"), _("Peptide level FDR"), _("Spectrum level FDR")], majorDimension=1,
                                               style=wx.RA_SPECIFY_ROWS)
        self.text_FDR_filter = wx.TextCtrl(self, wx.ID_ANY, _(default_params_dict['FDR_filter']))
        self.button_save = wx.Button(self, wx.ID_ANY, _("Save parameters ..."))
        self.Bind(wx.EVT_BUTTON, self.SaveParams, self.button_save)
        self.button_load = wx.Button(self, wx.ID_ANY, _("Load parameters ..."))
        self.Bind(wx.EVT_BUTTON, self.LoadParams, self.button_load)
        self.text_save_folder = wx.TextCtrl(self, wx.ID_ANY, "")
        self.button_save_path = wx.Button(self, wx.ID_ANY, _("..."))
        self.Bind(wx.EVT_BUTTON, self.SavePath, self.button_save_path)
        self.button_run_prolucid = wx.Button(self, wx.ID_ANY, _("Run ProLuCID and DTASelect"))
        self.Bind(wx.EVT_BUTTON, self.RunProlucid, self.button_run_prolucid)
        self.button_rerun_dta = wx.Button(self, wx.ID_ANY, _("Re-run DTASelect only"))
        self.Bind(wx.EVT_BUTTON, self.RunDTA, self.button_rerun_dta)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ProLuCID_GUI.__set_properties
        self.SetTitle(_("ProLuCID GUI by Yu (Tom) Gao @ Yates Laboratory"))
        self.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_MENU))
        self.combo_box_enzyme_specificity.SetSelection(default_params_dict['enzyme_spec'])
        self.combo_box_diff_mod.SetSelection(default_params_dict['diff_mod'])
        self.combo_box_DTA_ends.SetSelection(default_params_dict['DTA_min_num_tryptic_end'])
        self.radio_box_FDR_level.SetSelection(default_params_dict['FDR_level'])
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ProLuCID_GUI.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)

        label_1 = wx.StaticText(self, wx.ID_ANY, _("FASTA file:"), style=wx.ALIGN_RIGHT)
        sizer_2.Add(label_1, 1, wx.ALIGN_CENTER, 0)
        sizer_2.Add(self.text_fasta, 5, wx.ALIGN_CENTER, 0)
        sizer_2.Add(self.button_fasta_path, 1, wx.ALIGN_CENTER, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        label_2 = wx.StaticText(self, wx.ID_ANY, _("Java path:"), style=wx.ALIGN_RIGHT)
        sizer_3.Add(label_2, 1, wx.ALIGN_CENTER, 0)
        sizer_3.Add(self.text_java, 5, wx.ALIGN_CENTER, 0)
        sizer_3.Add(self.button_java_path, 1, wx.ALIGN_CENTER, 0)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        label_3_1 = wx.StaticText(self, wx.ID_ANY, _("Java max memory(Xmx):"), style=wx.ALIGN_CENTER)
        label_3_2 = wx.StaticText(self, wx.ID_ANY, _("Total threads:"), style=wx.ALIGN_CENTER)
        sizer_3_1.Add(label_3_1, 1, wx.ALIGN_CENTER, 0)
        sizer_3_1.Add(self.text_java_xmx, 1, wx.ALIGN_CENTER, 0)
        sizer_3_1.Add(label_3_2, 1, wx.ALIGN_CENTER, 0)
        sizer_3_1.Add(self.text_java_thread, 1, wx.ALIGN_CENTER, 0)
        sizer_1.Add(sizer_3_1, 1, wx.EXPAND, 0)
        label_3 = wx.StaticText(self, wx.ID_ANY, _("MS2 file path:"), style=wx.ALIGN_RIGHT)
        sizer_4.Add(label_3, 1, wx.ALIGN_CENTER, 0)
        sizer_4.Add(self.text_ms2s, 5, wx.ALIGN_CENTER, 0)
        sizer_4.Add(self.button_ms2_path, 1, wx.ALIGN_CENTER, 0)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)
        label_4 = wx.StaticText(self, wx.ID_ANY, _("Precursor tolerance (ppm):"), style=wx.ALIGN_CENTER)
        sizer_5.Add(label_4, 1, wx.ALIGN_CENTER, 0)
        sizer_5.Add(self.text_precursor_ppm, 1, wx.ALIGN_CENTER, 0)
        label_5 = wx.StaticText(self, wx.ID_ANY, _("Number of isotopes:"), style=wx.ALIGN_CENTER)
        sizer_5.Add(label_5, 1, wx.ALIGN_CENTER, 0)
        sizer_5.Add(self.text_num_isotope, 1, wx.ALIGN_CENTER, 0)
        sizer_1.Add(sizer_5, 1, wx.EXPAND, 0)
        label_6 = wx.StaticText(self, wx.ID_ANY, _("Precursor starts (Da):"), style=wx.ALIGN_CENTER)
        sizer_6.Add(label_6, 1, wx.ALIGN_CENTER, 0)
        sizer_6.Add(self.text_min_mass, 1, wx.ALIGN_CENTER, 0)
        label_7 = wx.StaticText(self, wx.ID_ANY, _("Precursor ends (Da):"), style=wx.ALIGN_CENTER)
        sizer_6.Add(label_7, 1, wx.ALIGN_CENTER, 0)
        sizer_6.Add(self.text_max_mass, 1, wx.ALIGN_CENTER, 0)
        sizer_1.Add(sizer_6, 1, wx.EXPAND, 0)
        label_8 = wx.StaticText(self, wx.ID_ANY, _("Protease name:"), style=wx.ALIGN_CENTER)
        sizer_7.Add(label_8, 1, wx.ALIGN_CENTER, 0)
        sizer_7.Add(self.text_protease, 1, wx.ALIGN_CENTER, 0)
        label_9 = wx.StaticText(self, wx.ID_ANY, _("Cleavage residues:"), style=wx.ALIGN_CENTER)
        sizer_7.Add(label_9, 1, wx.ALIGN_CENTER, 0)
        sizer_7.Add(self.text_cleave_residue, 1, wx.ALIGN_CENTER, 0)
        sizer_1.Add(sizer_7, 1, wx.EXPAND, 0)
        label_10 = wx.StaticText(self, wx.ID_ANY, _("Enzyme specificity:"), style=wx.ALIGN_CENTER)
        sizer_8.Add(label_10, 1, wx.ALIGN_CENTER, 0)
        sizer_8.Add(self.combo_box_enzyme_specificity, 1, wx.ALIGN_CENTER, 0)
        label_11 = wx.StaticText(self, wx.ID_ANY, _("Maximum missed cleavage:"), style=wx.ALIGN_CENTER)
        sizer_8.Add(label_11, 1, wx.ALIGN_CENTER, 0)
        sizer_8.Add(self.text_max_miss_cleave, 1, wx.ALIGN_CENTER, 0)
        sizer_1.Add(sizer_8, 1, wx.EXPAND, 0)
        label_12 = wx.StaticText(self, wx.ID_ANY, _("Static modification:"), style=wx.ALIGN_CENTER)
        sizer_9.Add(label_12, 1, wx.ALIGN_CENTER, 0)
        sizer_9.Add(self.text_stat_mod, 1, wx.ALIGN_CENTER, 0)
        label_13 = wx.StaticText(self, wx.ID_ANY, _("Differential modification:"), style=wx.ALIGN_CENTER)
        sizer_9.Add(label_13, 1, wx.ALIGN_CENTER, 0)
        sizer_9.Add(self.combo_box_diff_mod, 1, wx.ALIGN_CENTER, 0)
        sizer_1.Add(sizer_9, 1, wx.EXPAND, 0)
        label_16 = wx.StaticText(self, wx.ID_ANY, _("C-term static mod:"), style=wx.ALIGN_CENTER)
        sizer_13.Add(label_16, 1, wx.ALIGN_CENTER, 0)
        sizer_13.Add(self.text_c_term_stat_mod, 1, wx.ALIGN_CENTER, 0)
        label_17 = wx.StaticText(self, wx.ID_ANY, _("N-term static mod:"), style=wx.ALIGN_CENTER)
        sizer_13.Add(label_17, 1, wx.ALIGN_CENTER, 0)
        sizer_13.Add(self.text_n_term_stat_mod, 1, wx.ALIGN_CENTER, 0)
        sizer_1.Add(sizer_13, 1, wx.EXPAND, 0)
        label_14 = wx.StaticText(self, wx.ID_ANY, _("Min # of peptide/protein:"), style=wx.ALIGN_CENTER)
        sizer_11.Add(label_14, 1, wx.ALIGN_CENTER, 0)
        sizer_11.Add(self.text_DTA_min_num_peptide, 1, wx.ALIGN_CENTER, 0)
        label_15 = wx.StaticText(self, wx.ID_ANY, _("Min # of tryptic end:"), style=wx.ALIGN_CENTER)
        sizer_11.Add(label_15, 1, wx.ALIGN_CENTER, 0)
        sizer_11.Add(self.combo_box_DTA_ends, 1, wx.ALIGN_CENTER, 0)
        sizer_1.Add(sizer_11, 1, wx.EXPAND, 0)
        sizer_12.Add(self.radio_box_FDR_level, 3, wx.ALIGN_CENTER, 0)
        sizer_12.Add(self.text_FDR_filter, 1, wx.ALIGN_CENTER, 0)
        sizer_1.Add(sizer_12, 1, wx.EXPAND, 0)
        sizer_14.Add(self.button_save, 1, wx.ALIGN_CENTER, 0)
        sizer_14.Add(self.button_load, 1, wx.ALIGN_CENTER, 0)
        sizer_1.Add(sizer_14, 1, wx.EXPAND, 0)
        label_18 = wx.StaticText(self, wx.ID_ANY, _("Result file output folder:"), style=wx.ALIGN_CENTER)
        sizer_15.Add(label_18, 1, wx.ALIGN_CENTER, 0)
        sizer_15.Add(self.text_save_folder, 3, wx.ALIGN_CENTER, 0)
        sizer_15.Add(self.button_save_path, 0, wx.ALIGN_CENTER, 0)
        sizer_1.Add(sizer_15, 1, wx.EXPAND, 0)
        sizer_16.Add(self.button_run_prolucid, 1, wx.ALIGN_CENTER, 0)
        sizer_16.Add(self.button_rerun_dta, 1, wx.ALIGN_CENTER, 0)
        sizer_1.Add(sizer_16, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def onOpenFasta(self, event):
        """"""
        with wx.FileDialog(
                self, message="Choose a file",
                defaultFile="",
                wildcard="Fasta file (*.fasta;*.FASTA)|*.fasta;*.FASTA|" \
                         "All files (*.*)|*.*",
                style=wx.FD_OPEN | wx.FD_DEFAULT_STYLE | wx.FD_CHANGE_DIR
        ) as dlg:
            # self.list_ctrl_3.DeleteAllItems()
            if dlg.ShowModal() == wx.ID_CANCEL:
                return

            paths = dlg.GetPaths()
            for index, path in enumerate(paths):
                self.text_fasta.SetValue(path)

    def onOpenJava(self, event):
        """"""
        with wx.FileDialog(
                self, message="Choose a file",
                defaultFile="",
                wildcard="Java.exe (java.exe;JAVA.EXE)|java.exe;JAVA.EXE|" \
                         "All files (*.*)|*.*",
                style=wx.FD_OPEN | wx.FD_DEFAULT_STYLE | wx.FD_CHANGE_DIR
        ) as dlg:
            # self.list_ctrl_3.DeleteAllItems()
            if dlg.ShowModal() == wx.ID_CANCEL:
                return

            paths = dlg.GetPaths()
            for index, path in enumerate(paths):
                self.text_java.SetValue(path)

    def onOpenMS2(self, event):
        """"""
        with wx.FileDialog(
                self, message="Choose a file",
                defaultFile="",
                wildcard="ms2 files (*.ms2;*.MS2)|*.ms2;*.MS2|" \
                         "All files (*.*)|*.*",
                style=wx.FD_OPEN | wx.FD_MULTIPLE | wx.FD_CHANGE_DIR
        ) as dlg:
            # self.list_ctrl_3.DeleteAllItems()
            if dlg.ShowModal() == wx.ID_CANCEL:
                return

            paths = dlg.GetPaths()
            temp_path_list = []
            for index, path in enumerate(paths):
                temp_path_list.append(path)
            self.text_ms2s.SetValue(';'.join(temp_path_list))

    def SaveParams(self, event):
        with wx.FileDialog(
                self, message="Choose a file",
                defaultFile="",
                wildcard="Params file (*.prolucid_params)|*.prolucid_params|" \
                         "All files (*.*)|*.*",
                style=wx.FD_SAVE | wx.FD_CHANGE_DIR
        ) as dlg:
            if dlg.ShowModal() == wx.ID_CANCEL:
                return
            paths = dlg.GetPaths()

        params_dict = {}
        params_dict['java_path'] = self.text_java.GetValue()
        params_dict['fasta_path'] = self.text_fasta.GetValue()
        params_dict['precursor_ppm'] = self.text_precursor_ppm.GetValue()
        params_dict['num_isotope'] = self.text_num_isotope.GetValue()
        params_dict['min_mass'] = self.text_min_mass.GetValue()
        params_dict['max_mass'] = self.text_max_mass.GetValue()
        params_dict['protease'] = self.text_protease.GetValue()
        params_dict['cleave_residue'] = self.text_cleave_residue.GetValue()
        params_dict['enzyme_spec'] = self.combo_box_enzyme_specificity.GetSelection()
        params_dict['max_miss_cleave'] = self.text_max_miss_cleave.GetValue()
        params_dict['stat_mod'] = self.text_stat_mod.GetValue()
        params_dict['diff_mod'] = self.combo_box_diff_mod.GetValue()
        params_dict['c_term_stat_mod'] = self.text_c_term_stat_mod.GetValue()
        params_dict['n_term_stat_mod'] = self.text_n_term_stat_mod.GetValue()
        params_dict['DTA_min_num_peptide'] = self.text_DTA_min_num_peptide.GetValue()
        params_dict['DTA_min_num_tryptic_end'] = self.combo_box_DTA_ends.GetSelection()
        params_dict['FDR_level'] = self.radio_box_FDR_level.GetSelection()
        params_dict['FDR_filter'] = self.text_FDR_filter.GetValue()
        params_dict['java_xmx'] = self.text_java_xmx.GetValue()
        params_dict['java_thread'] = self.text_java_thread.GetValue()

        with open(paths[0], 'wb') as file_out:
            file_out.write(json.dumps(params_dict))

    def LoadParams(self, event):
        with wx.FileDialog(
                self, message="Choose a file",
                defaultFile="",
                wildcard="Params file (*.prolucid_params)|*.prolucid_params|" \
                         "All files (*.*)|*.*",
                style=wx.FD_OPEN | wx.FD_CHANGE_DIR
        ) as dlg:
            if dlg.ShowModal() == wx.ID_CANCEL:
                return
            paths = dlg.GetPaths()

        params_dict = json.load(open(paths[0], 'rb'))

        self.text_java.SetValue(params_dict['java_path'])
        self.text_fasta.SetValue(params_dict['fasta_path'])
        self.text_precursor_ppm.SetValue(params_dict['precursor_ppm'])
        self.text_num_isotope.SetValue(params_dict['num_isotope'])
        self.text_min_mass.SetValue(params_dict['min_mass'])
        self.text_max_mass.SetValue(params_dict['max_mass'])
        self.text_protease.SetValue(params_dict['protease'])
        self.text_cleave_residue.SetValue(params_dict['cleave_residue'])
        self.combo_box_enzyme_specificity.SetSelection(params_dict['enzyme_spec'])
        self.text_max_miss_cleave.SetValue(params_dict['max_miss_cleave'])
        self.text_stat_mod.SetValue(params_dict['stat_mod'])
        self.combo_box_diff_mod.SetValue(params_dict['diff_mod'])
        self.text_c_term_stat_mod.SetValue(params_dict['c_term_stat_mod'])
        self.text_n_term_stat_mod.SetValue(params_dict['n_term_stat_mod'])
        self.text_DTA_min_num_peptide.SetValue(params_dict['DTA_min_num_peptide'])
        self.combo_box_DTA_ends.SetSelection(params_dict['DTA_min_num_tryptic_end'])
        self.radio_box_FDR_level.SetSelection(params_dict['FDR_level'])
        self.text_FDR_filter.SetValue(params_dict['FDR_filter'])
        self.text_java_xmx.SetValue(params_dict['java_xmx'])
        self.text_java_thread.SetValue(params_dict['java_thread'])

    def SavePath(self, event):
        with wx.DirDialog(
                self, "Choose input directory", "",
                        wx.DD_DEFAULT_STYLE | wx.DD_DIR_MUST_EXIST
        ) as dlg:
            if dlg.ShowModal() == wx.ID_CANCEL:
                return
            path = dlg.GetPath()
        # print path
        self.text_save_folder.SetValue(path)

    def RunProlucid(self, event):
        ms2_files = [i for i in self.text_ms2s.GetValue().split(';') if i.endswith('.ms2')]
        # print ms2_files
        if len(ms2_files) > 0:
            search_dir = os.path.dirname(ms2_files[0])
            os.chdir(search_dir)
            with open('search.xml', 'wb') as search_xml:
                search_xml.write('<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!--Parameters for ProLuCID database search-->\n')
                search_xml.write('<parameters>\n')
                search_xml.write('<database>\n<database_name>%s</database_name>\n<is_indexed>false</is_indexed>\n</database>\n' % self.text_fasta.GetValue())
                search_xml.write(
                    '<search_mode>\n<primary_score_type>1</primary_score_type>\n<secondary_score_type>2</secondary_score_type>\n<locus_type>1</locus_type>\n<charge_disambiguation>0</charge_disambiguation>\n<atomic_enrichement>0</atomic_enrichement>\n<min_match>0</min_match>\n<peak_rank_threshold>200</peak_rank_threshold>\n<candidate_peptide_threshold>500</candidate_peptide_threshold>\n<num_output>5</num_output>\n<is_decharged>0</is_decharged>\n<fragmentation_method>CID</fragmentation_method>\n<multistage_activation_mode>0</multistage_activation_mode>\n<preprocess>1</preprocess>\n</search_mode>\n')
                search_xml.write(
                    '<isotopes>\n<precursor>mono</precursor>\n<fragment>mono</fragment>\n<num_peaks>%s</num_peaks>\n</isotopes>\n<tolerance>\n<precursor_high>3000</precursor_high>\n<precursor_low>3000</precursor_low>\n<precursor>%s</precursor>\n<fragment>600</fragment>\n</tolerance>\n' % (
                        self.text_num_isotope.GetValue(), self.text_precursor_ppm.GetValue()))
                search_xml.write('<precursor_mass_limits>\n<minimum>%s</minimum>\n<maximum>%s</maximum>\n</precursor_mass_limits>\n' % (
                    self.text_min_mass.GetValue(), self.text_max_mass.GetValue()))
                search_xml.write('<precursor_charge_limits>\n<minimum>0</minimum>\n<maximum>1000</maximum>\n</precursor_charge_limits>\n')
                search_xml.write('<peptide_length_limits>\n<minimum>6</minimum>\n</peptide_length_limits>\n')
                search_xml.write('<num_peak_limits>\n<minimum>25</minimum>\n<maximum>5000</maximum>\n</num_peak_limits>\n<max_num_diffmod>5</max_num_diffmod>\n')
                search_xml.write('<modifications>\n<display_mod>0</display_mod>\n')
                if len(self.text_n_term_stat_mod.GetValue()) > 0:
                    search_xml.write(
                        '<n_term>\n<static_mod>\n<symbol>*</symbol>\n<mass_shift/>\n</static_mod>\n<diff_mods>\n<diff_mod>\n<symbol>*</symbol>\n<mass_shift>%s</mass_shift>\n</diff_mod>\n</diff_mods>\n</n_term>\n' % self.text_n_term_stat_mod.GetValue())
                else:
                    search_xml.write(
                        '<n_term>\n<static_mod>\n<symbol>*</symbol>\n<mass_shift/>\n</static_mod>\n<diff_mods>\n<diff_mod>\n<symbol>*</symbol>\n<mass_shift>%s</mass_shift>\n</diff_mod>\n</diff_mods>\n</n_term>\n' % '0.0')
                if len(self.text_c_term_stat_mod.GetValue()) > 0:
                    search_xml.write(
                        '<c_term>\n<static_mod>\n<symbol>*</symbol>\n<mass_shift/>\n</static_mod>\n<diff_mods>\n<diff_mod>\n<symbol>*</symbol>\n<mass_shift>%s</mass_shift>\n</diff_mod>\n</diff_mods>\n</c_term>\n' % self.text_c_term_stat_mod.GetValue())
                else:
                    search_xml.write(
                        '<c_term>\n<static_mod>\n<symbol>*</symbol>\n<mass_shift/>\n</static_mod>\n<diff_mods>\n<diff_mod>\n<symbol>*</symbol>\n<mass_shift>%s</mass_shift>\n</diff_mod>\n</diff_mods>\n</c_term>\n' % '0.0')

                # static mods
                search_xml.write('<static_mods>\n')
                stat_mods = [(i.split(' ')[0], i.split(' ')[1]) for i in self.text_stat_mod.GetValue().split(';') if (len(i) > 3 and ' ' in i)]
                for each in stat_mods:
                    search_xml.write('<static_mod>\n<symbol>*</symbol>\n<mass_shift>%s</mass_shift>\n<residue>%s</residue>\n</static_mod>\n' % (each[0], each[1]))
                search_xml.write('</static_mods>\n')
                # diff mods
                search_xml.write('<diff_mods>\n')
                diff_mods = [(i.split(' ')[0], i.split(' ')[1]) for i in self.combo_box_diff_mod.GetValue().split(';') if (len(i) > 3 and ' ' in i)]
                for each in diff_mods:
                    search_xml.write('<diff_mod>\n<symbol>*</symbol>\n<mass_shift>%s</mass_shift>\n<residues>\n' % each[0])
                    for residue in each[1]:
                        if residue.upper() in 'ARNDCQEGHILKMFPSTWYV':
                            search_xml.write('<residue>%s</residue>\n' % residue.upper())
                    search_xml.write('</residues>\n</diff_mod>\n')
                search_xml.write('</diff_mods>\n</modifications>\n')

                # enzyme info
                search_xml.write(
                    '<enzyme_info>\n<name>%s</name>\n<specificity>%s</specificity>\n<max_num_internal_mis_cleavage>%s</max_num_internal_mis_cleavage>\n<type>true</type>\n<residues>\n' % (
                        self.text_protease.GetValue(), self.combo_box_enzyme_specificity.GetValue()[0], self.text_max_miss_cleave.GetValue()))

                cleavage_residue = [i.upper() for i in self.text_cleave_residue.GetValue() if i.upper() in 'ARNDCQEGHILKMFPSTWYV']
                for residue in cleavage_residue:
                    search_xml.write('<residue>%s</residue>\n' % residue)
                search_xml.write('</residues>\n</enzyme_info>\n')
                search_xml.write('<advanced_params>\n<scan_number>0</scan_number>\n</advanced_params>\n')
                search_xml.write('</parameters>')

            run_prolucid.write_prolucid(search_dir)
            run_prolucid.write_dtaselect(self.text_save_folder.GetValue())
            run_prolucid.RunProlucid(self.text_java.GetValue(), search_dir, self.text_java_xmx.GetValue(), int(self.text_java_thread.GetValue()), search_dir, self.text_save_folder.GetValue(),
                                     os.path.join(search_dir, 'search.xml'),
                                     ms2_files)
            run_prolucid.run_dtaselect(os.path.join(self.text_save_folder.GetValue(),
                                                    'Filtered_result_%s_%s' % (FDR_level_dict[self.radio_box_FDR_level.GetSelection()], self.text_FDR_filter.GetValue())),
                                       self.text_save_folder.GetValue(), self.text_java.GetValue(),
                                       self.text_DTA_min_num_peptide.GetValue(), self.combo_box_DTA_ends.GetValue()[0],
                                       FDR_level_dict[self.radio_box_FDR_level.GetSelection()],
                                       self.text_FDR_filter.GetValue(), self.text_fasta.GetValue())
            os.chdir(search_dir)
            shutil.move('search.xml', self.text_save_folder.GetValue())

    def RunDTA(self, event):
        run_prolucid.write_dtaselect(self.text_save_folder.GetValue())
        run_prolucid.run_dtaselect(os.path.join(self.text_save_folder.GetValue(),
                                                'Filtered_result_%s_%s' % (FDR_level_dict[self.radio_box_FDR_level.GetSelection()], self.text_FDR_filter.GetValue())),
                                   self.text_save_folder.GetValue(), self.text_java.GetValue(),
                                   self.text_DTA_min_num_peptide.GetValue(), self.combo_box_DTA_ends.GetValue()[0],
                                   FDR_level_dict[self.radio_box_FDR_level.GetSelection()],
                                   self.text_FDR_filter.GetValue(), self.text_fasta.GetValue())


# end of class ProLuCID_GUI


if __name__ == "__main__":
    gettext.install("app")  # replace with the appropriate catalog name

    app = wx.App(False)
    frame_1 = ProLuCID_GUI(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
